### ISSUE TITLE
Player Movement Jitters Back and Forth in Async Mode

### ISSUE THREAD

**Issue by DoubleStyx** [Frozenreflex/Thundagun#4]
In async mode, Unity will redraw stale states to improve HMD responsiveness. However, this causes player movement to jitter between two states: an up-to-date orientation/position and an older orientation/position (presumably the last one from Resonite's update). I'm not sure exactly what causes this, but I hypothesize it's related to some connector that tries to drive the Unity avatar position directly, bypassing the RenderTask queue.

**Comment by DoubleStyx** [comment]
Merged with #6.

**Comment by DoubleStyx** [comment]
If we fix the IK and buffering issues, this might actually resolve on its own. #6 and #40.

**Comment by DoubleStyx** [comment]
Buffering is technically not an issue here anymore, but I still think this is related to some connector or update order weirdness.

**Comment by DoubleStyx** [comment]
This doesn't happen on the native Linux build for some reason. Huh.

**Comment by DoubleStyx** [comment]
I suspect the charactercontroller might be driven by Unity as part of a fixed physics update loop

The fixed update occurs regardless of the engine update time, which is good for physics accuracy but bypasses the packet queueing we're doing

**Comment by Nytra** [comment]
Would be kinda fixed by https://github.com/Frozenreflex/Thundagun/pull/78

**Comment by rabbuttz** [comment]
https://github.com/user-attachments/assets/0f0add90-9177-4eef-9e98-c21fb47a287d
looks still exist in low fps environment for me

**Comment by Nytra** [comment]
This can resolved by enabling the new EmulateVanilla option, but it doesn't solve the underlying issue

**Comment by troyBORG** [comment]
> This can resolved by enabling the new EmulateVanilla option, but it doesn't solve the underlying issue

Where did we find that option? It says the last build was three weeks ago. Wasn't that added in some update that hasn't been built yet?

**Comment by Nytra** [comment]
It has been committed to the repo but not in a release yet

**Comment by DoubleStyx** [comment]
A new release has been made with the EmulateVanilla option. I want to track down the exact cause of this issue, because that option is mostly for desktop users. Incidentally it hides this issue, but it isn't a solution for VR users.

https://github.com/Frozenreflex/Thundagun/releases/tag/1.2.0

**Comment by Nytra** [comment]
I have a vague feeling this might be caused by some error in the SlotConnector code, but that code is a nightmare to decipher
